export function html_to_text(html) {
    return html
        .replace(/<style([\s\S]*?)<\/style>/gi, '')
        .replaceAll('<br>', '\n')
        .replaceAll('&nbsp;', ' ')
        .replaceAll('&amp;', '&')
        .replaceAll('&lt;', '<')
        .replaceAll('&gt;', '>')
        .replaceAll('&quot;', '"')
        .replaceAll('&apos;', "'")
        .replaceAll('&cent;', '¢')
        .replaceAll('&pound;', '£')
        .replaceAll('&yen;', '¥')
        .replaceAll('&euro;', '€')
        .replaceAll('&copy;', '©')
        .replaceAll('&reg;', '®')
        .replaceAll('&trade;', '™')
        .replaceAll('&times;', '×')
        .replaceAll('&divide;', '÷')
        .replace(/<[^>]*>/g, '\n')
        .split('\n')
        .filter((x) => x.trim() !== '')
        .join('\n')
        .trim();
}